[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["rm -f package-lock.json", "npm install"]

[phases.build]
cmds = ["echo 'No build step required for Node.js API'"]

[start]
cmd = "npm start" 